### ISSUE TITLE
[theora] Packet was not a Theora header

### ISSUE THREAD

**Issue by quan1992** [ros-perception/image_transport_plugins#4]
Hi jkammerl, I installed 1.8.20 theora_image_transport on my laptop, but when I run "rosrun image_view image_view image:=/camera/image_raw theora", I got the new warning "[theora] Packet was not a Theora header" and it seems theora doesn't work at all because the video streaming is very laggy.

After I installed the total image_transport_plugin stack instead of only theora_image_transport package, the warning disappears but it seems still doesn't work because video streaming is very laggy. And there is another problem, when I try to republish theora image to raw image, "[theora] Packet was not a Theora header" appears again. 

compressed_image_transport works well. 

the bandwidth of /camera/image_raw/compressed is around 1MB, but the bandwidth of /camera/image_raw/theora is only around 5KB. I am not sure if it's right.

Thanks!

**Comment by jkammerl** [comment]
There is a general flaw in the design on the theora transport plugin. The libtheora encoder uses the OGG container format which is not designed to be used for streaming at all. The encoder starts with the first ROS subscriber and it transmits the header packet followed by the video packets. Accordingly, a second subscriber that subscribes later to the topic (for instance rosbag) will miss the header packet and therefore cannot decode the video. 

Fixing this would require to basically rewrite the whole plugin and design different message types that allow to resend headers and a certain rate and furthermore signal the content of each compressed image packet (header/data). Even this approach would be a hack since there are other streaming formats out there which encode "header" information along with the stream. Hence, since theora is kind of outdated, it would make more sense to focus on the integration of a more recent codes, such as vp8 into ROS.
