### ISSUE TITLE
melodic release?

### ISSUE THREAD

**Issue by furushchev** [ros-perception/image_transport_plugins#67]
There are major changes between melodic release version and the latest tagged version in this repository.
Is there any plan to release to melodic?

**Comment by ghost** [comment]
In melodic, the compressedDepth transport doesn't offer the RVL compression algorithm. The last melodic release is based on the `indigo-devel` branch. I have no idea why the `noetic-devel` branch isn't compiled for melodic as well since I was able to compile it from source. 
https://index.ros.org/r/image_transport_plugins/github-ros-perception-image_transport_plugins/#melodic
